from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName('Main')
        Main.resize(467, 851)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('designer\\../assets/icon.ico'),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        Main.setStyleSheet(
            '/* 浅色模式 */\n/*QLineEdit {\n    background-color: rgb(240, 240, 240);\n}*/\n\n/* 深色模式 */\n/*background-color: rgb(24, 26, 27);\ncolor: rgb(255, 255, 255);*/\n')
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName('centralwidget')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.head_info_bar = QtWidgets.QWidget(self.centralwidget)
        self.head_info_bar.setObjectName('head_info_bar')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.head_info_bar)
        self.verticalLayout.setObjectName('verticalLayout')
        self.title = QtWidgets.QLabel(self.head_info_bar)
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName('title')
        self.verticalLayout.addWidget(self.title)
        self.slogan = QtWidgets.QLabel(self.head_info_bar)
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.slogan.setFont(font)
        self.slogan.setAlignment(QtCore.Qt.AlignCenter)
        self.slogan.setObjectName('slogan')
        self.verticalLayout.addWidget(self.slogan)
        self.ver_name = QtWidgets.QLabel(self.head_info_bar)
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.ver_name.setFont(font)
        self.ver_name.setAlignment(QtCore.Qt.AlignCenter)
        self.ver_name.setObjectName('ver_name')
        self.verticalLayout.addWidget(self.ver_name)
        self.verticalLayout_2.addWidget(self.head_info_bar)
        spacerItem = QtWidgets.QSpacerItem(
            20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.settings = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(12)
        self.settings.setFont(font)
        self.settings.setObjectName('settings')
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settings)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.widget = QtWidgets.QWidget(self.settings)
        self.widget.setObjectName('widget')
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName('gridLayout_4')
        self.autorun = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(13)
        self.autorun.setFont(font)
        self.autorun.setObjectName('autorun')
        self.gridLayout_4.addWidget(self.autorun, 0, 0, 1, 1)
        self.play_time_group = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(10)
        self.play_time_group.setFont(font)
        self.play_time_group.setObjectName('play_time_group')
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.play_time_group)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.play_time = QtWidgets.QLineEdit(self.play_time_group)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.play_time.sizePolicy().hasHeightForWidth())
        self.play_time.setSizePolicy(sizePolicy)
        self.play_time.setMinimumSize(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(11)
        self.play_time.setFont(font)
        self.play_time.setAcceptDrops(False)
        self.play_time.setObjectName('play_time')
        self.horizontalLayout_4.addWidget(self.play_time)
        self.gridLayout_4.addWidget(self.play_time_group, 4, 3, 1, 1)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(13)
        self.hide_progress_bar = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(13)
        self.hide_progress_bar.setFont(font)
        self.hide_progress_bar.setObjectName('hide_progress_bar')
        self.gridLayout_4.addWidget(self.hide_progress_bar, 4, 0, 1, 1)
        self.show_notice_win = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(13)
        self.show_notice_win.setFont(font)
        self.show_notice_win.setObjectName('show_notice_win')
        self.gridLayout_4.addWidget(self.show_notice_win, 4, 1, 1, 1)
        self.no_weekend = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(13)
        self.no_weekend.setFont(font)
        self.no_weekend.setObjectName('no_weekend')
        self.gridLayout_4.addWidget(self.no_weekend, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.settings)
        self.widget_2.setObjectName('widget_2')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.duration = QtWidgets.QGroupBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(10)
        self.duration.setFont(font)
        self.duration.setObjectName('duration')
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.duration)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.duration_slider = QtWidgets.QSlider(self.duration)
        self.duration_slider.setMinimum(1)
        self.duration_slider.setMaximum(30)
        self.duration_slider.setPageStep(1)
        self.duration_slider.setProperty('value', 15)
        self.duration_slider.setOrientation(QtCore.Qt.Horizontal)
        self.duration_slider.setObjectName('duration_slider')
        self.horizontalLayout_2.addWidget(self.duration_slider)
        self.duration_txt = QtWidgets.QLabel(self.duration)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.duration_txt.setFont(font)
        self.duration_txt.setObjectName('duration_txt')
        self.horizontalLayout_2.addWidget(self.duration_txt)
        self.horizontalLayout.addWidget(self.duration)
        self.volume = QtWidgets.QGroupBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(10)
        self.volume.setFont(font)
        self.volume.setObjectName('volume')
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.volume)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.volume_slider = QtWidgets.QSlider(self.volume)
        self.volume_slider.setMaximum(100)
        self.volume_slider.setPageStep(1)
        self.volume_slider.setProperty('value', 80)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName('volume_slider')
        self.horizontalLayout_3.addWidget(self.volume_slider)
        self.volume_txt = QtWidgets.QLabel(self.volume)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.volume_txt.setFont(font)
        self.volume_txt.setObjectName('volume_txt')
        self.horizontalLayout_3.addWidget(self.volume_txt)
        self.horizontalLayout.addWidget(self.volume)
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.settings)
        self.widget_6.setObjectName('widget_6')
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_6.setObjectName('gridLayout_6')
        self.video_source_group = QtWidgets.QGroupBox(self.widget_6)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(10)
        self.video_source_group.setFont(font)
        self.video_source_group.setObjectName('video_source_group')
        self.gridLayout_5 = QtWidgets.QGridLayout(self.video_source_group)
        self.gridLayout_5.setObjectName('gridLayout_5')
        self.everyday_switch = QtWidgets.QRadioButton(self.video_source_group)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(11)
        self.everyday_switch.setFont(font)
        self.everyday_switch.setObjectName('everyday_switch')
        self.gridLayout_5.addWidget(self.everyday_switch, 1, 0, 1, 1)
        self.jrsf_source = QtWidgets.QRadioButton(self.video_source_group)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(11)
        self.jrsf_source.setFont(font)
        self.jrsf_source.setObjectName('jrsf_source')
        self.gridLayout_5.addWidget(self.jrsf_source, 0, 1, 1, 1)
        self.xw30f_source = QtWidgets.QRadioButton(self.video_source_group)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(11)
        self.xw30f_source.setFont(font)
        self.xw30f_source.setObjectName('xw30f_source')
        self.gridLayout_5.addWidget(self.xw30f_source, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.video_source_group, 0, 0, 1, 1)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(10)
        # self.gridLayout_3.setObjectName('gridLayout_3')
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(10)
        # self.horizontalLayout_7.setObjectName('horizontalLayout_7')
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(11)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(10)

        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(11)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(11)
        font = QtGui.QFont()
        font.setFamily('Segoe UI')
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ad_check_group = QtWidgets.QGroupBox(self.widget_6)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(10)
        self.ad_check_group.setFont(font)
        self.ad_check_group.setObjectName('ad_check_group')
        self.gridLayout_8 = QtWidgets.QGridLayout(self.ad_check_group)
        self.gridLayout_8.setObjectName('gridLayout_8')
        self.ad_check_wait_txt = QtWidgets.QLabel(self.ad_check_group)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(11)
        self.ad_check_wait_txt.setFont(font)
        self.ad_check_wait_txt.setObjectName('ad_check_wait_txt')
        self.gridLayout_8.addWidget(self.ad_check_wait_txt, 0, 0, 1, 1)
        self.ad_check_wait = QtWidgets.QLineEdit(self.ad_check_group)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ad_check_wait.sizePolicy().hasHeightForWidth())
        self.ad_check_wait.setSizePolicy(sizePolicy)
        self.ad_check_wait.setMinimumSize(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(11)
        self.ad_check_wait.setFont(font)
        self.ad_check_wait.setAcceptDrops(False)
        self.ad_check_wait.setObjectName('ad_check_wait')
        self.gridLayout_8.addWidget(self.ad_check_wait, 0, 1, 1, 1)
        self.max_ad_check = QtWidgets.QLineEdit(self.ad_check_group)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.max_ad_check.sizePolicy().hasHeightForWidth())
        self.max_ad_check.setSizePolicy(sizePolicy)
        self.max_ad_check.setMinimumSize(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(11)
        self.max_ad_check.setFont(font)
        self.max_ad_check.setAcceptDrops(False)
        self.max_ad_check.setObjectName('max_ad_check')
        self.gridLayout_8.addWidget(self.max_ad_check, 1, 1, 1, 1)
        self.max_ad_check_txt = QtWidgets.QLabel(self.ad_check_group)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(11)
        self.max_ad_check_txt.setFont(font)
        self.max_ad_check_txt.setObjectName('max_ad_check_txt')
        self.gridLayout_8.addWidget(self.max_ad_check_txt, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.ad_check_group, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_6, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.settings)
        self.auto_test_group = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(12)
        self.auto_test_group.setFont(font)
        self.auto_test_group.setObjectName('auto_test_group')
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.auto_test_group)
        self.verticalLayout_4.setObjectName('verticalLayout_4')
        self.widget_4 = QtWidgets.QWidget(self.auto_test_group)
        self.widget_4.setObjectName('widget_4')
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_8.setObjectName('horizontalLayout_8')
        self.test_times_txt = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.test_times_txt.setFont(font)
        self.test_times_txt.setObjectName('test_times_txt')
        self.horizontalLayout_8.addWidget(self.test_times_txt)
        self.test_times_edit = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.test_times_edit.setFont(font)
        self.test_times_edit.setMouseTracking(False)
        self.test_times_edit.setAcceptDrops(False)
        self.test_times_edit.setFrame(False)
        self.test_times_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.test_times_edit.setObjectName('test_times_edit')
        self.horizontalLayout_8.addWidget(self.test_times_edit)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.auto_test_group)
        self.widget_5.setObjectName('widget_5')
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_9.setObjectName('horizontalLayout_9')
        self.test_duration_txt = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily('黑体')
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.test_duration_txt.setFont(font)
        self.test_duration_txt.setObjectName('test_duration_txt')
        self.horizontalLayout_9.addWidget(self.test_duration_txt)
        self.test_duration_edit = QtWidgets.QLineEdit(self.widget_5)
        font = QtGui.QFont()
        font.setFamily('等线')
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.test_duration_edit.setFont(font)
        self.test_duration_edit.setMouseTracking(False)
        self.test_duration_edit.setAcceptDrops(False)
        self.test_duration_edit.setFrame(False)
        self.test_duration_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.test_duration_edit.setObjectName('test_duration_edit')
        self.horizontalLayout_9.addWidget(self.test_duration_edit)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.bottom_btns = QtWidgets.QWidget(self.auto_test_group)
        self.bottom_btns.setObjectName('bottom_btns')
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottom_btns)
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.jrsf_test = QtWidgets.QPushButton(self.bottom_btns)
        font = QtGui.QFont()
        font.setFamily('微软雅黑')
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.jrsf_test.setFont(font)
        self.jrsf_test.setStyleSheet(
            'color: rgb(255, 255, 255);\nborder-radius:6px;\nbackground-color: rgb(0, 170, 255);')
        self.jrsf_test.setFlat(False)
        self.jrsf_test.setObjectName('jrsf_test')
        self.horizontalLayout_5.addWidget(self.jrsf_test)
        self.xw30f_test = QtWidgets.QPushButton(self.bottom_btns)
        font = QtGui.QFont()
        font.setFamily('微软雅黑')
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.xw30f_test.setFont(font)
        self.xw30f_test.setStyleSheet(
            'color: rgb(255, 255, 255);\nborder-radius:6px;\nbackground-color: rgb(193, 161, 0);')
        self.xw30f_test.setFlat(False)
        self.xw30f_test.setObjectName('xw30f_test')
        self.horizontalLayout_5.addWidget(self.xw30f_test)
        self.verticalLayout_4.addWidget(self.bottom_btns)
        self.verticalLayout_2.addWidget(self.auto_test_group)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 467, 23))
        self.menubar.setObjectName('menubar')
        self.theme_menu = QtWidgets.QMenu(self.menubar)
        self.theme_menu.setObjectName('theme_menu')
        Main.setMenuBar(self.menubar)
        self.action_light = QtWidgets.QAction(Main)
        self.action_light.setObjectName('action_light')
        self.action_dark = QtWidgets.QAction(Main)
        self.action_dark.setObjectName('action_dark')
        self.theme_menu.addAction(self.action_light)
        self.theme_menu.addAction(self.action_dark)
        self.menubar.addAction(self.theme_menu.menuAction())
        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate('Main', '自动新闻播放器'))
        self.title.setText(_translate('Main', '自动新闻播放器'))
        self.slogan.setText(_translate('Main', '- 看你想看，享你所想 -'))
        self.ver_name.setText(_translate('Main', 'App版本：v1.0.0 正式版'))
        self.settings.setTitle(_translate('Main', '默认设置'))
        self.autorun.setText(_translate('Main', '开机自启动'))
        self.play_time_group.setTitle(_translate('Main', '播放时间'))
        self.play_time.setText(_translate('Main', '18:50:00'))
        self.hide_progress_bar.setText(_translate('Main', '隐藏进度条'))
        self.show_notice_win.setText(_translate('Main', '显示右下角提示窗'))
        self.no_weekend.setText(_translate('Main', '周末不播'))
        self.duration.setTitle(_translate('Main', '播放时长(预计)'))
        self.duration_txt.setText(_translate('Main', '15min'))
        self.volume.setTitle(_translate('Main', '播放音量'))
        self.volume_txt.setText(_translate('Main', '80%'))
        self.video_source_group.setTitle(_translate('Main', '默认播放源'))
        self.everyday_switch.setText(_translate('Main', '每天轮播'))
        self.jrsf_source.setText(_translate('Main', '今日说法'))
        self.xw30f_source.setText(_translate('Main', '新闻30分'))
        self.ad_check_group.setTitle(_translate('Main', '广告检测'))
        self.ad_check_wait_txt.setText(_translate('Main', '检测延时(s)'))
        self.ad_check_wait.setText(_translate('Main', '1.5'))
        self.max_ad_check.setText(_translate('Main', '5'))
        self.max_ad_check_txt.setText(_translate('Main', '最大检测次数'))
        self.auto_test_group.setTitle(_translate('Main', '自动化测试'))
        self.test_times_txt.setText(_translate('Main', '请输入测试次数'))
        self.test_times_edit.setText(_translate('Main', '1'))
        self.test_duration_txt.setText(_translate('Main', '请输入播放时长'))
        self.test_duration_edit.setText(_translate('Main', '15'))
        self.jrsf_test.setText(_translate('Main', '今日说法'))
        self.xw30f_test.setText(_translate('Main', '新闻30分'))
        self.theme_menu.setTitle(_translate('Main', '颜色主题'))
        self.action_light.setText(_translate('Main', '浅色主题'))
        self.action_dark.setText(_translate('Main', '深色主题'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
